import {NextIntlClientProvider, useMessages} from 'next-intl';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/src/app/[locales]/components/Navbar";
import Footer from "@/src/app/[locales]/components/Footer";
import Dropdown from "@/src/app/[locales]/components/Dropdown";
import HeaderMobile from "@/src/app/[locales]/components/NavbarMobile";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Katarzyna Kuta",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>)
 {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <body className="bg-aspargus-50">
        <NextIntlClientProvider messages={messages}>
           <Navbar />
             <HeaderMobile />  
               <main className="flex flex-col justify-center items-center flex-grow overflow-hidden">
                {children}
               </main>
           <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
