import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Dropdown from "@/components/Dropdown";
import HeaderMobile from "@/components/NavbarMobile";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Katarzyna Kuta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-aspargus-50">
          <Navbar />
            <HeaderMobile />  
              <main className="flex flex-col justify-center items-center flex-grow overflow-hidden">
                {children}
              </main>
          <Footer />
      </body>
    </html>
  );
}
